[project]
name = "discord-match-history"
version = "0.1.0"
description = "Discord Bot that brings back match history"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord>=2.3.2",
    "python-dotenv>=1.1.1",
]
